var PixelRenderer = (function() {
    function R() {}

    R.prototype.init = function(canvas) {
        this.RESOLUTION = 64;
        this.canvas = canvas;
        this.gc = canvas.getContext('2d');
        this.pixelSize = canvas.width / this.RESOLUTION;

        // Disable smoothing for crisp edges when scaling images
        this.gc.mozImageSmoothingEnabled = false;
        this.gc.msImageSmoothingEnabled = false;
        this.gc.imageSmoothingEnabled = false;
    }

    // xi, yi = pixel position index
    R.prototype.drawPixel = function(xi, yi) {
        var p = this.pixelSize;
        this.gc.fillRect(xi * p, yi * p, p, p);
    }

    // Draws an image
    // x, y = screen coordinates
    R.prototype.drawImage = function(img, x, y) {
        var p = this.pixelSize;
        var pos = this.screenCoordToPixel(x, y);
        this.gc.drawImage(img, pos.x * p, pos.y * p, img.width * p, img.height * p);
    }

    // Draws not pixel text, for debugging purposes
    // x, y = screen coordinates
    R.prototype.drawText = function(text, x, y, size) {
        this.gc.save();
        this.gc.fillStyle = 'white';
        this.gc.strokeStyle = 'black';
        this.gc.textBaseline = 'hanging';
        if (size === undefined) size = this.pixelSize * 4;
        this.gc.font = size + 'px verdana';
        this.gc.fillText(text, x, y);
        this.gc.strokeText(text, x, y);
        this.gc.restore();
    }

    // Converts a screen position into pixel indices
    R.prototype.screenCoordToPixel = function(x, y) {
        x = Math.round(x / this.pixelSize);
        y = Math.round(y / this.pixelSize);
        return {x:x, y:y};
    }

    // Converts pixel indices into screen position
    R.prototype.pixelCoordToScreen = function(x, y) {
        x = x * this.pixelSize;
        y = y * this.pixelSize;
        return {x:x, y:y};
    }

    R.prototype.clear = function() {
        this.gc.clearRect(0, 0, this.canvas.width, this.canvas.height);
    }

    return R;
})();

var Glyph = (function() {
    function G(fontImg, charCode, x, y, w, h, xoffset, yoffset, xadvance) {
        this.fontImg = fontImg;
        this.charCode = charCode;
        this.x = x;
        this.y = y;
        this.width = w;
        this.height = h;
        this.xoffset = xoffset;
        this.yoffset = yoffset;
        this.xadvance = xadvance;

        this.canvasSlice = document.createElement('canvas');
        this.canvasSlice.width = w;
        this.canvasSlice.height = h;
        var gc = this.canvasSlice.getContext('2d');
        gc.drawImage(this.fontImg, x, y, w, h, 0, 0, w, h);
    }

    return G;
})();

var BitmapFontRenderer = (function() {
    // fontInfo = JSON data generated by BMFont
    function F(fontImg, fontInfo) {
        fontInfo = JSON.parse(fontInfo).font;
        this.lineHeight = fontInfo.common.lineHeight;

        function toInt(str) {
            return parseInt(str, 10);
        }

        // Create glyph map
        this.glyphs = {};
        for (var i=0; i<fontInfo.chars.count; ++i) {
            var cInfo = fontInfo.chars.char[i];
            var glyph = new Glyph(fontImg, cInfo.id, toInt(cInfo.x), toInt(cInfo.y), toInt(cInfo.width), toInt(cInfo.height), toInt(cInfo.xoffset), toInt(cInfo.yoffset), toInt(cInfo.xadvance));
            this.glyphs[glyph.charCode] = glyph;
        }
    }

    F.prototype.createStaticString = function(string) {
        var canvas = document.createElement('canvas');
        var gc = canvas.getContext('2d');
        var cumulativeWidth = 0;
        for (var i=0; i<string.length; ++i) {
            var charCode = string.charCodeAt(i);
            var glyph = this.glyphs[charCode];
            if (glyph !== undefined) {
                gc.drawImage(glyph.canvasSlice, cumulativeWidth, glyph.yoffset);
                cumulativeWidth += glyph.xadvance;
            }
        }
        return canvas;
    }

    return F;
})();
